### ISSUE TITLE
Why no parametres for middleware?

### ISSUE THREAD

**Issue by luminarious** [egoist/majo#4]
I like what you're doing here, it's perfect for my use-case (making a basic static site). But one question, why can't middleware have any parametres at all? In my case, it would be preferable if options were set like `.use(render({pretty: true}))` so I could reuse the render function in other streams as well.

Or am I missing something simple? 🤔
```
async function render(stream) {
	for (const file in stream.files) {
		const options = {pretty: true}
		const contents = await pug.renderFile(file, opions)
		stream.createFile(file + '.html', {contents})
	}
}
```

**Comment by egoist** [comment]
Just create A higher order functiom then:

```js
function render(options) {
  return stream => {
    // do something
  }
}

youCanNow.use(render(options))
```

**Comment by luminarious** [comment]
That's exactly the thing, thank you!
